version: "3.8"

services:
  api:
    build: .
    container_name: rinha-api
    ports:
      - "9999:8080"
    networks:
      - payment-processor
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha

  db:
    image: postgres:16-alpine
    container_name: rinha-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true

volumes:
  pgdata:
