version: "3.8"

services:
  api:
    build: .
    container_name: rinha-api
    ports:
      - "9999:8080"
    networks:
      - payment-processor
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    container_name: rinha-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true

volumes:
  pgdata:
